version: '3.4'

services:

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y

  ordermanager.api:
    image: ${DOCKER_REGISTRY-}ordermanagerapi
    build:
      context: .
      dockerfile: src/OrderManager.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sql-server
