@OrderManager.Api_HostAddress = http://localhost:8080

POST {{OrderManager.Api_HostAddress}}/v1/users/register
Content-Type: application/json
Accept: application/json

{
    "email": "sadasp",
    "password": "sd"
}

###


GET {{OrderManager.Api_HostAddress}}/products/
Accept: application/json

###

POST {{OrderManager.Api_HostAddress}}/orders/
Content-Type: application/json
Accept: application/json

{
    "date": "2023-05-10",
    "temperatureC": 30,
    "summary": "Warm"
}

###
